# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    - id: pretty-format-json
      args:
        - "--autofix"
        - "--indent=4"
        - "--no-sort-keys"

-   repo: local
    hooks:
    -   id: ruff-format
        name: Ruff Formatter
        entry: ruff format ./src
        language: python
        types_or: [ python, pyi, jupyter ]
        # Run formatter first
        stages: [pre-commit]
        pass_filenames: false # Format based on project context
        additional_dependencies: ["ruff>=0.11.3"]

    -   id: ruff-lint
        name: Ruff Linter
        entry: ruff check --fix ./src
        language: python
        types_or: [ python, pyi, jupyter ]
        # Run linter after formatter
        stages: [pre-commit]
        pass_filenames: false # Lint based on project context
        additional_dependencies: ["ruff>=0.11.3"]

    -   id: mypy
        name: Mypy Type Check
        entry: mypy src --config-file pyproject.toml
        language: python
        types_or: [ python, pyi ]
        # Run type checker last
        stages: [pre-commit]
        pass_filenames: false # Mypy needs project context
        additional_dependencies: ["mypy>=1.15.0"]
